import os
import time as cabdulahi

def prRed(skk): print("\033[91m {}\033[00m" .format(skk)) 
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk)) 
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk)) 
def prLightPurple(skk): print("\033[94m {}\033[00m" .format(skk)) 
def prPurple(skk): print("\033[95m {}\033[00m" .format(skk)) 
def prCyan(skk): print("\033[96m {}\033[00m" .format(skk)) 
def prLightGray(skk): print("\033[97m {}\033[00m" .format(skk)) 
def prBlack(skk): print("\033[98m {}\033[00m" .format(skk)) 

green = '\033[32;1m'

gta = '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'

white = '\033[1;37m' # White 
red = '\033[31m' # red
orange = '\033[33m' # orange
blue = '\033[34m' # blue
p  = '\033[35m' # purple
C  = '\033[36m' # cyan


class banner:
    def __init__(self):
        print C+orange+"""
                                                ...   ......'',;;;;;;;;;;;;;,,,,,''''...................................  .    ..:dxxxxxxdolc:::;,,'.'''....'''...''''.''''''',,,;;cloddxkOOOOOOOOOOkkkkkkkkxkxxxxxxxxxxxxxxxdddddoollolllllllllllllllllooolllllllllllcccccccccc:::::;;;;;;;;;,,;;;
                                                        ....   ......'',,,;;;;;;;;,,,''',,''''''''....................................';coxxoc:;;,''.........................................''',:cloxk000OOOOkkkkkkkkkkxkkkkkxxxxkkxxddddoollooolllllllllllllllooollllllllllllllcccccc:::::;;;;;;;;;;;;;;;;
                                                          .............''''',,,,''''.'''','',,,,''..................'..............;loddoc:,'....'''''......'''.''''''..................''.''...''''',:ldkO00Okkkkkkkkkkkkkkkkkkxxxxxddooooooooooolllllllllllllllooollllllllllllcccccc:::;;;;;;;;;;,,,;;;;;:
                                                              .........................'',,,;;;,'...       ........''...........;lddoc;,'...................'''..''........'''..........''.''...''.....',:oxOOkkkkkkkxkkxkkkkkkkkxxxddoooooooooolllllllllllllllllooollllllllllllcccc::::;;;;;;;;;;;,,,;;;;;;
                                                               ..          .............',,;;;;,...       ......''......... .':odoc,'.................................................'''...'...''.....'..';lxkkkkkxxdxxxxxxxxxxxxxxdddooooooooollllllllllllllloooooollllllllllcccc:::::;;;;;;;;;;,,;;;;;;;;
                                                               .              . .........'',,,'...       ........'.......  .:ooc;'.................'.....................................'.''......''''''...':lxkkxxxxxxdxxxxxxxxxxxddddddooooooooollloolllloooooooolllllllllllcc::::::;;;;;;;;;;;;;;;;,;;;;
                                                              ..                 ........''''....        .....'''......  .;loc;,'.................''..................'''.........................''''''......,cdkkxxxxddxxxkxxxxxdddddoodddddooooooooooooooooooooollllllllllccc::::::::;;;;;;;;;;;;;;;,;;;;
                                                              ..                  ..............        ....'''''....  ..coc;'..''...........................................................''..''''''........';oxxxxxxxxxxxxxxxdddddddooddddooollllllloooooooooooollllllccccc:::::::::::::::;;;;;;;;;;;,,,
......                                                                             ............       .....'',''....  .'cl:'.'.........''.......''''................................................''......'...';lxkxxxxxxxxxxxdddddddddodddooolllllooooooooooooooolllllcccccc::::ccccccc:::;;;;;;;;;;;;,,,
.''.....                                                       .                   ............      ......',,,'.... .'cc;'.......'.................''...............................................''''...'''''';lxkxxxxdxxxddddddddddddddddooolooooooooooooooollllllllcccccc::cccccclc:::::;;;;;;;;;;;;;;
''''....'''...                                                  ....               .....''.....      ...'',;,,,'.....'ll,..''....'......'''....'.............................................................'''''':dxxxxxdxxxddddddddddddddddddooooooooooooooooolllllllllllcccccccccccccc:::::::;;;;;;;;;;;
''''''',:c::;'...                 ...','....                    ......           ......''''....     ...',;;;;,,'....'cl;'......'................................       ....  ................................'''''.,ldxxxxdxxxddddddddddddddddddooooooooooooooollllllcccllllllccccccccccccc::::::;:;;;;:::::
;::c:::ccccccc;,..               .';codol:,..            ..     .......        ........'',''......   ..',,;;;,''...,cl;'''''...''........................                      ..       .....................'''''.'coxxdddddddddddddddddddddddddodddooooooooollllcccccllllllllccccccccccccc::::;::::;::cccc
ccccc:::;;;::c:;'.              ..;coxxxxo:,..                   ......      .........'',,,'''....   ....',,,,'...'col,.....'''''..................        .....'''''',,,,,'',''''.......   ...............'''''''..;lxxdddddddddddddddddddddddddooooooooolllllllccccccllllllllllcccccccccc:::::::::::::ccll
c::;,'.....';:::,'.....        ..,:ldxxkxdl;'..         ...      ......     ......''...',,,,''.....  .....'''''..';ll;'................................',:codxxkkOOOOkkkkkxxddddoollcc:;,....  ............'''''''..,ldxdddxddddddddddddddddddddoooooooloollllllccllllllllllllllcclccccccccc::::::cccccccllo
'.....    ..';:::;''''...     ..';lodxkxdol:,..          ..       .....     ...........'',,''..............''....'coc'......................  ..;lxkkOOO0KKXXXXXXXXXXXXXXXXXXXXXKKKKK0Okdoc:,'.................''...,ldxdddxddddddddddddddddddddoooolllllllllllllllllllllllllllllclllcccccccccccccllcccllllo
...        ..,:cc:;,,,;,'... ...,cldxkkkdol:;..          ..        .......  ..............................'''''..,lo:'..................    .':dOKNNXXKKXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNXK0Okxl:'.. ............'...,lxkxdxxxdddddddddddddddddddoollllllcclllcclllllllllcccccllllllllllllccccccclllllclllloo
.............,:clc:;,;:::;'....':codxkkkxol:,..         ..        ........   ....................''...''''''''''';ll;'................     ':dOKKKKKXXXKKXXXXXNNNNNNNNXXXNNNNNNNNNNNNNNNWWWNXXK0Odc'.. .........'''',lxxxxxxxdddddddddddddddooooooolllllcccccccccccccllccccccclllllllllllllllllllllllccclllo
''''''''''''',;clc:;,;:cllc;,',;clodxkxxdol:,...       ..         .. .....   ..................',,,,,,,,,,''''''':ol,'............       .,ok00KKKKKKXXXXXXXXXXXXXNNNNNXXNNNNNNWWWNNNNNNNNNNNNNNNNXOd:'..........'.';lxxddddddddddddddddoooooooooooooolllccccccccccccccccccllloooooooooolllllllllllllcccclll
,,;;;;;;;;,;,;;:ccc:;::looolc:::clodkkxdolc;,....        .      . ..........     ............',,;:::;;;;;,,,,''',cdl,.............      .:x000KKKKKXXXXXXXXNNNNNNWWWWWNNNNNNNNNNNWWWWWWWWWWNNNNWNNWWWXOdc'.........':oxdoddxddddddooooooooooooodoooooooolllccccccccccclllllllooooooooooooooolllllllccccccccl
:::::cccc::::::ccccc:::clodollcccldxkkkxolc;'....                 .........      ..........',;;;::::::;;;;;,,,'';ldl,...........       .;xKXKKXXXXXXXXXXXNNNXXK000000KKXNNWWWWNNNWWWWWWWWWWWWWWWNNNNNWWWXOo;......',coddddddddooooooooollllooooooddddddooolcccccccccllllooloooooooooddddooollllllllccccccccc
::::::::cccc::cccllc:::cloddollllodkkkxdol:,.. ...        .......... ......       ......',,;:::::cccc::;;:;;,,',:ooc,........         .:kKXKKXXXXXXXNNNNNX0kolllcccc::ccloxOKNNWWWWWWNNNNNWNNNNNNWWNNNWWWNX0d;....';coddddoooooooooooolllllooooooddddddooollcccccclllllooooooooooooooooooooooolllllccccccccc
,,,,,,,,,,,,,,,,;::cc::cloddoollodxkOkxdl:;'.....         .......  ........   .   ....',,;;::c::::cc::::;;;,,,',cll;'......          .:kXNXKKXXNNNNNNNNNXK0000KXXKKK0Oxoc;,,;cd0XWWWWNNNNNWNNNWWNNNWWWWWWNNNXOo,..,:ldddooooooooooooooolllloooooooddddoooollcccccllllloooooooooooooooooooollllllllccccllcccc
''''''',,''''''',,;:ccccclooooooodxkkxxdoc;,,'...       .      .    ........ ... .....',;:::::c:::::;;;;;,,,,,,;clc:'....           .;kNNNNXXXXNNNNNNNNNNNWWMMWWWWWWWWWNXKko;'';lxOXNWWWWWWWWWWWNNWWWWWNWWNXXXKd;,;lodoooooooooooooooollooooooooooooooooollcccccllllllloooooooooolloooooollllllllllcccclllll
,,,,,,,,,,''''''',;::ccccloooooodddddddddooooc;.......   ..   .... ................''',;:::::c::::;;,,,,,,,,,,,;clll,..            .ckXWNNNNXXNNNNNWWWWWWWWMMMWWWWWWWWWWWWNXKOo:'';lkKNWWNNWWWWWWWWWWWWWWNNNXXNXkollooooodddooooooooooooooolllllllllllllllllllllcclllllloooodddooooolloollllllllllllccclllll
,,,,,,;;;,,,,,,,,,;::ccclllooooooodddddddxxxdl;.......          ..................',,,;::::::::;;;,,,'''',,,,,,:lodo:..           .:kXNNNNWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNWWNKkl,..ckXWWWWWWWWWWWWWWWWWWNNXXXXKkollooooooooooooooooolllllllllcllllllllllllllllllllllllllooooooollllllcllllccllllccllllllll
,,,,,;;;;;;;;;;::;;::ccclllloooooodddddxxxxdl;..............    .................',,,;;::::::::;;,,''''''',,,',coodo;.           .,xXWNNNWWWNNNWWWWWWWWWWWWWWWWWWWNNWWWWNNWWNNNWNKx:..;dKWMWWWWWWWWWWWWWWWWWNNXXK0xolloooooooddooooolllllllllcccccccccccllllllllllllllllllllllllllllccccccccccclllllllllllll
:;;,,,,,;;;;::::::::::ccllloooooddddddddxdoc;'......''''''''.....................',;;;;:::::::;;;;,'...''''''',cool:.           .,dKNNNNWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWWNNNNN0o'.,dKWMWWWWWWWWWWWWWNNNNNNNNKkollooooooooollllllllllllccc::::::::cccccclllllllllllllllllllllllcccccccccccllllllllllcccc
lllc;;,,,,;;;;:::::::::ccloooooodooddddool:;,'',,,,;;;;:::::;;;;,'...............',,,,;:::::::;;;,,''..''''''';cooc;.          .,dKNNNNWWWWWWWWWNNNNNNNWNNNNNXK000000KXNWWNNNNNNNXNNXkookXWWWWNXKOkxxxxdxO0XNNNNXKxllloolloollllllllccllllccc::::::::::cccccccccccllllllllllcllcccccccccccccccllllcccccc::::
oodolcc:::::::::::::;;:cllooooooddddxxdlc::;;::::::::cccccccclllc:;,...............'''';;:;;::;;,,'''..'''''',;lddddoc:'.     .'dKXKXNWWWWWWWWWWWWWWWWWNNWNNKkl;'''',:oxO0KNNNNNNNNWWNNNNWWWWNOl;'.......';cdkKNNKxlclllclllllcclllcccccccccc::::;;;:::::cccccccccccccccllccllc:ccccccccccccclllllcc::::::::
lllooooolllllcc:;;;;;;;:lloooooodddddoolcccccccccccccllllloooddddolc;,'..............'',,,,,,,,,,''...''''.'',:dO0KKKK0ko:,...'l0XOkKNWWWNWWWWWWWMMMMMMWWWWWX0xlc:;,''',,;lkXNNNNNNWWWWWWWWMWN0dc:::cccccc:,',cx0Kklccccccccccccllllllcccccc::::::;;;;::::::::::::::ccccccccccc::cccccccccccccccccccccc:::::
lllllooolllllcc:;;;;;;;:cloooooodddoolllllllooooodddddddxxxxkkkkkkkxdl:'.................'''''''''....','''',;oOKK0O00O0K0OdlldONXO0XWWNWWWWMMMWWMMMMMMWWWWWWWNNX0Oxol:;,..;d0XXNNWWMMWWWMMWWWNXXXXNNXXXXXXKkoc:oOkocc:cccccccccclllllccccc:::::::;;;::::::;;;;;;::::::ccccccccccccccccccccccccccc::::::::::
lllllcclllcccc:::::;;;;:cloooooddddoooddddddxxkkkkkkkkkkkkkOOOOOOOOkxdc,...........   ................',,,;,;lx0K0OO000OkO00OOKXNKOKNWWNWWWWWWWWMMMMMMMMMWWWWWWWWWWNXK0Okxoox0XNWWWWWWWWWWMWNNNNNNNNNNNWNNWNNNKOxxxllccccccccccccllllccccc:::::::;;;;:;;::;;;;;;;;;;;:::ccccccc::ccccccccccccc:::::;;;;;:::;
lllllccccccccc:::cllcc::clodddddddxxxxkkkkkkkOOOOkkkOOOOkkkkkxxdddoll:,'...........          . .......',;::;:x000O00000OkkO0O0XNNXKNWWWNWWNNNNWWWMMMMMMMMMWWWMMMWWWMMWWWWNNXXNWWWWWWWWWWWWWWNXXXXNNNNWWWNNNNNNWWN0dlccccccccccccccccccccccc::::::::::::::;;;;;;;;;;;;;;;::ccccc::cccccccccccc::::;;;;;;;:::;
cllllccccccclc:;:lodoolllodddxxkkkkxxxkkkkkkkkkkkxxkkkkkkkkxddolc:;;,,''...........              ....'',;:;;lOK0000KKKK0OkkOO0XWWWWWMWWNWWNNXXNWWWMMWWWWMMMMMMMMMMMMMMMMMMWWWMMMMMMMWWWWWWWWNXXNNNWWWWWNNNNNNNWWWXklcccccccccccccccccccccccc::::::::::::::;;;;;;;;:;;;;;;::::cc::::::ccc:::::::;;;;;,,;;;:;;
;:cccccccccccc:;:cooooodddxkkkkxxdooooloooooddddddddxxxxxxxxdddoollccc::;,'.........              ....',;;;:oOK00KKK0OkdlcldOXWMWWWWWWWNWWWNNNWWWWWWWWWWWWMMMMMWMMMMMMMWMMMMMMMMMMMMWWWWWWMWWNK0000KXXNWWNNNNNNNNXkolclllcccccccccccc::::::::::::::::::::;;;;;;;;;;;;;;,,;::::c:::::::::::::::::;;;;;;;;;;;;
.',;:::cc:cclc:;:clllooddxxkkkxdoollccccccllooooodddddddddxxxxxxdddddddool:;''''.....             . ...',,,;ck0KXXX0kdolllokKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWWWMMMMMMMMMMMMMMWMMMMWWWWWWWWWXkl:::codk0XNNNNNNNN0xolllllclllcccccccc:::::::::cc:::::::::::;;;;;;;;;;;;,,;;:::::::::::::::::::::;;;;;;;;;;;;
...',;::cccllc:::cllloooooddxkkxxdollllllooddddddddooooooodoooodoooddxxxxxdl:,'''....                 ......'lkKXXXKOxxxkkO0KNWWWWWWWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWMMMMMMMMMWWWMMMMMMWWWWMMWWWN0koc:;;;:lxOXNNNNNX0dollllllllcccccccccccc:::::::::cc::::::::;;;;;;;:;;;;;;;;;:::::::::::::::::::::;;;;;;;;;;;
  ...,;ccccccc::cclooooollloddxddolcclloodxxxxxxxddddddddddddoollllllloodxxoc,''''....                 .. ...'lOKXKKKK000OOO0XWWWWWWWWWWWWWWNNNNNWWWWWWWNXXXXXXNWWWWWWWWWMWWWMMMMWWWWWMMMMWWWWWNX0kdollcccxXNNNNXOollllllllccccccccccc::::::::::ccccccccc:cc:::::::;;;;;;;;;;::::::::::::::::::::::;;;;;;;;;
   ..,;cccccc:::cloollllcc:cllcccccclodddddddxxxxxxxxxdddxxxdddddddoollllool::;;,,'...                     ....lk0000XXXXK0O0XWMWWWWWWWWWWWWNNWWWWWWNXKK0000KKKXNWWWWWWWWWWWWWMMMMMMMMMMMMWWWWWWWWNXK0kxl;cONNNNKklcllllllllcccccccc:::::cccccclccllllllllcccccc::::::::;;;;;::::::::::::;::::::::::;;;;;;;;
   ..,;:cllcc:::cllcccccc::ccccccclooddddlc::ccooddddxxddxxxdddxxxxxxxddoooollllc:;,'...               .........:xKK00KXKKKKKXWWWWWWWWWWWWWWWWWNNXK0OkkkkkO000KKNWWWWMMMMMMWWWWMMMMMMMWWWWWWMWWWWWWWWNNX0kk0NNNXOollccllllllcccccccccc::::ccclllllooooooollcccccccc:::::::::::::::::::::::::::::::::::::;;;;
  ..',;:cllc::::::::::::cc::ccccloddxddol:,.....';cloddxxxxxdddddxxxkxxxxxxxxxxddolc:,'....  .............'','...;xKXXXXKKKKKXNWWWWWWWWWWWWWWNXK00OkkxxxkkOOOO0XWWWWWMMMMMWWWWWWWWWWWWWWWWWWWMMMWWWWWWWWWWNXXNNKxlcccclllllccccllccccccccccllooooodddddxddoolllllllcccccc:::::::::::cccc:::::::::::::::::;;;
...',;:clllc::;;:::::::c::::cllodxxxddoc,..      ..',:clodxxxxxxddddxxxxxxxxkkkkxxddolc:;'............',,,;,;,.. .,d0XNXKKKKKKNWWWWWWWWWWWWMMWNXK0OkxxxxxxkOO0KNWWWWWWWMMMWWWWWWWWWWWWWWWWWWWWWWWMMMMWWWWWNNNNX0xlcccclllllllllllllllccccllloodddddxxxxxxxdoooolllllllccccccc:::::::::cc::::::::::::::::::::
cccccccclllc:;;;;;::::::::clodxxxxxol:;'..    .   . ...,;:clodxxxxddddddoddddxxxxxxxxxxdolc:,'........',,,;;;;,'.  .lk00000OkONWWWWWWWMMWWWMMWWNXK0kxddxxxxkOKKXNWWWWWWWMMWWWWWWWWWWWWWWWWNWWWWWWWWWWMMMWWWWWNXOdlcclcllllllllloooollllllooooodddxxkkkxxxxddooollllllllllllccc:::::::::::::::::::::::;;;;;;;
ddddolllool:;;,,,;;::::cclodxxxxdoc;'..         ..    ....'';:cloddddddddddoooooodxxkkkOOkxddlc;'....',,;,;;;cl;.  .,oxxxdoolxXWWWWWWWWWWWWWWWWWNXKOkxxxxdxO0K00KXXXXXNNWWWWWWWWWWWWWNNXNNNNNWWWNNWWWWWWWWMMWWXOdlclllollllloooooooooooloooddddxxkkOOOkkkxxxddooollllllllllcccc:::::::::;;;::::::::::;;;;;;;
oooddoddool:;;,,,;::cclodxxxxdol:,...               ...........',;clodxxxxxddoolllllooddxxkkOkxdl:,''',;;,,;:ll:'. .;dO0kdolldKWWWWMMMMWWWWWWWWWWNNK0OOOOkO0KKOO000OOO0KXNWWWWMMWWNNNXKOk0NWNNWWNWWWNNNNNNWWWWKkollooloooooooooddddddoooodddddxxkkkOOOkkkkkkxdddooooollllllllcccc:::::;;;;;;::::::::::;;;;;:
loooddddolc::;;;;cclloddxxxdoc;,..                  ...............',:cloxxxxdddoolcccllloodxkOOxo:''',,,',,;::,.  .ckXNX0kxdkKWWWWWMMWXKKKKXXNNNNNXKKKKKKKKXXKK0000OkkkOKXWWWWWWNXK0KOl;l0WNNNNWWWWNNNNXXNNWNKxoloooooooooooodddddddddddxxxxxxkkkkOOkkkOOOkkxxdoooooollllllllccccc::::;;;;;;:::::::::::::::
loodddddolc:::::cloodxxxdlc:;'...          ..       ...........     ....,:clddxxxxddoollccccloxkko:,'',,'''',;'..  ,dKNNX0OkkkOXWWWWMMNKOkkOO0000KKKKKKK0000KKKKXNNNXK0OOOOKNWWWWWWX0Okc.,xXWNNNNWWWWNNNNXXNWN0xolooooooooodddddddxxxxdddxxxkkkkkOOOkkkkOOOOOkxdddoooooooooooollccc:::::;;;;;;:::::::::::::c
lloodddolc::::clodddxxdl:,....                .      ..........  ...  .....,:cloddxxxxddolcccclool:,''''..',;::'  .c0NNNX0kkOkO0XNWMWWWX0OOOOOOOOOO0000000000000KKKKXNNNXXKXXXXXNNNNXXKo..cONWWWWWWWWWNNWNNWWXOdoooooooooodddddddxxxxxxdddxxkkkkkOOkkkkOOOOOOkkxxdddddddddddddoolcccc::::;::::::::::::::::::
cloooooolc::cclddddooc;'...                            ......... ..   ........';:codxxxkxdooolcccc:;,'......';;'. .oKNNXK0OOOOkkOKNWWWWWNXK00OOOOkkOOOO000000000000000KKXNNNNX0000XNXXNO:..:kXWNNNNWWWWWWWWWN0xolooooooooodddddddxxxxxxddxxkOOOOOOOOOkOOOOOOOOkkkxxxxxxxxxxxxxdooolcccccc:cccccccccccccccccc
;cloooollcclodddoc:;,'...                           ..  ...........   ..........',;:clodddddddoollcc:;'........   ,xXNNKOOOOOOOkkkOKNNNNNNXKK000OOkkxxxxxkkOOOOOOOOO000000KKKK0OkkOKKKXXKx;.'lkKNNWNNNNWNNNX0xocllloooooooddddddxxxxxxxddxxkkkOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkxxddoooolllllclllllllccccccccc
';cloooddoddxdlc;,.......                               ............   ...........',,,;:lodkkxxddoollc;'...... ..:xKNNX0OOOOOOOOOkOKXXKKKKKK00000OOkkxxddddxkOOOOOOO000OOOOO000OkxkKNXXXNN0o;.,cdkOxxOXNNNX0xollllloooooooddddddxxxxxxddxxxkkkOOOOOO0000000OOOOOOOOOOOOkkkkkkkkkxxxxxxxddoolllodooolllclllll
.';loddxxxxdo:,....................................     ...........  .............'',,,,;;cldxxxkkxdool:'......:xKWWWNNKOOOO00OO00KXX0OOOO000OOOOOOOOkkkkxxxkO000000000OO000OOOOOkO0XNWNNXNNKx;...',lOXWWNKkdooooollooooooddddddddxxxxddxxkkkkOOOOOOO0OO0000000000000OOOOOOOOOOOOOkkkkkkkxdooodxxxddddoooool
..,coddddoc:;,,,,,;;;;;:::::::::::::::;;;,,,'''''.................  .............'',,,,;;,,,;clodxxddddo;...'cxKNWWWWWWNXK0OO000KXNNXK0OOOO00OOOO00OOkkkkkkkkkkkkOO0KKKKK00OOOOkkkOKXXNNNWWWNN0xlclxKNNNNXOdooooooooooooooodddddddddxxdddxxkkkOOOOO0000000000000KKK0000000OOOOOOOOOOOOOOkxdoodxkOkkxxddddooo
',;coxxdolcccclloodoooooooooooooooooooollccccc:::::;,,,''''''....................'',,,,;;;,,,,'';:cloxxdc,,lONWWWNNWWWWWWNXXKKXXNNNNKOOOOOOOOOOOOOO00OOOOOOkkkxkxxkxkOXNNXKKKKK000KXNNNNNNNNNNNNXXNNWNNNKOxoooooooooooddddddddddddddxxxddxxkkOOOOOO00000KK000KKKKKKKKKKK000000000KKKKKK0OkdoodkOOOOkkkxxdddo
:ccodxxkxdolcc:::::::cclllloooddddddddxddddooolllllcccc:::::;;;,'................'',,,;;;:;;,,'.....,:clox0NWWWWWWWWNKOkxkkOKXNNNNNKOkOKK00000OkxxxxxkkkkOO0OOkkkkOkxkKNWNXKKXXXXXXNNNNNNNNNNNNNNNNWWNXKOxddddddddooodddddddddddddxxxxxxxxxkOO000000000KKKKKKKKKKKKKKK0000KKKKKKKKKKKKKK0OxooxO0000OOkkkxxdd
cccclodkkkxddoolc:;;;;;,,,;;;;;:cllooddddxxxdddddooooooooollllcc:;,........''....',,,;:clllllc;,'....':dKNWWWWWWWNXOkxxkO0KXNNWNNNNKOOKXXK0000000OOkkxxxkkkkkkkOOOOOOKNWWNK000KKKXXNNXXXNNWWNNNNWWNNNNKOxdddddddddddddddddddddddxxxxxxxxxxxkOO000000000KKKKKKKKKXXXXKKKKKKKXXXXXXXXXXKKKK0kdoxO00000OOkkxxdd
:::::cldkOOOOOOOOkxdolc::;;,'''''''',;:cccloddxxxxkxxxxxxxdoooollc:;,'........',:ldxxdddddxkOkkxxxkxxOKNWWWWWWWWNKkdxOXWWWWWWNNNNNNX0O0K0000OO0KKKKKK000K00OOOkkkxk0XNWWWWXK0000OO0KKKXXNNNNNWWNWNNXXKOxdddddddxddddddddddddddddxxxxxxxxxxxkOO000O000000KKKKKXXKKKXXXXXXXXXXXXXXXXXXXKKK0OxooxOKKKKK00Okxddd
cccccccldkkOOOOOOOkxxddoolcc::;;,,,'''..''',,;::cllooddxxxxxxxxddoolc:;;,',,:lx0KXNNXK0OkkOOOOkO00XXNNWWMWWMWWWXK0OkOKXNWNNNNNWNXXK0OOOOOOOOOOOO00000000KK0000OOkkOKNNNNNNNXXNNNXXXXKKXNNNNNNWWNNNXXKkddddddddddddxxxddxxxdddddddxxxxxxxddxxkOOOOO000000KKKKXXXXKKKXXXXXXXXXXXXXXXKKKKK00kdlldO0KKKK0Okxdddd
lllllc:cldxkOOOOOOkkxxxdooooollc:::::;;,,''.......'',;::cloodxxkkxxxddooodk0KNNWNWWWWWWWWNNNXKK0OOOOO0KNWWWWWNK00XXOO0XNNXXNNNXK0OOOkkkkkOOOkkOOOOOOOOOOOOOOOOO00OO0KKKKKXXKKKXNNWWNNNNNNNNNNWNNXXX0kxdddddddxxxxxxxxxxxxxxxxddxxxxxxxxddxxxkkOOOO000000KKKKKKKKKXXXXXXXXXXXXXXXXXKKKK00Oxollok00000Okxddddd
::cllclllooxOOOOOOOkkkxdddooooddolcc::::;;;;;,,,'..........,,;:clodxkOO0KXWWWWWWWWWWWWWWWWNXXKKKKKK0kxxxk0XNNKO0XXKkOKNNXXXXXK0OkkkkOOkxkkkkkOOO000OOOOOOOOOOOOOOO00OOOOOOkOO00KKXXNNNNNWWWWNNNNNXKkddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxddxxxxkkOOO0000000KKKKKKKKKXXXKKKKKXXXXXXKKKXXK0OxdolloxO000Okxdddodd
''',;;:cccldkOOO000Okkxxdddooodxxxxdolcc::::::::;;,''....   .,coxkkOOOO0XNWWWWWNXXXNWWWMWXOkOOOOO0O0000OOOO00kkKNNXKXNXXKKKK0OkxkkkOOOOkkkOkkkOO00000OOOOOO000OkxxkO0KKK0xc:okOOO0KKXXXNNNNNNNNNXKkdddddxxxddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOO000000000000KKKKXXXKKKKKKKKKKKKKKKK0OkdollcldkOOOkdooooodd
.......',;coxkOOO000OkkxkxxdoolodxkOkxdollcc::::::::;;,'.',:oO00Okxxxk0XXNWWMWWNXXXNWWWWWN0kkkkkxxxkkO0KXXK0kdxKNNXXK000000OkkkkkkkkOOOOOOOOOOOO00OOOxxdddddxxdlccdO0OO00koldxxdxxkkO0KKKKKXXXXKOxdddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOOOO000O00000000KKKKKK0KKKKKKKKKKK0000kxollccloxkkxdlllloddd
;,'.......';:okO0000OOkkkkkkxdolllodxkkxxdolcc:::::::::loxkkkxkkdllx0XXXXKNWMMMWWWXKXXNWWNX0kkOOO0KKXXXNNNKOdoxXNXKK0OOOOOkkkkkkkkkkkOOO0OOO000O00Oxodxdoooooolcclk00Okkkxxdxxxxkkxddxk0KKKKXXXKkdodxxdxxxxxxxxxxxxxxdxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOOO00000000000KK0000000KKKKK00000Okxolllllldxxdolccloodd
cc:;;,'......;ok0K0OOOOkOOOOOkxdlc:cldxkkxxxdoolc::;;:lx0OdooooloxOKXXKKKKXWMMWWNKkxkOKNWWNX0Oxxk0KNWWWWNNKkdlxKNKOOOOOOkkkkkkkkOOOOOOOO0O00000000kocdOkdooooolllok0KK00OkxoodkKXXK0OxkOKKKKXXNX0kxddxxxxxxxxxxxxxxdxxxxxxxxxxxxxxxxxxxxxxxxxxkkOOOOOOOOOOOOOO0000000000000000000OOOkkxdolllcccoddolcccclloo
lllllc:;,''..':dk00OO00OkxkOOOOkxdllllllodxxkxxdolcccokKKOxdolldOXNXKKKKXXXNWMWWNKOo:,cxKNWWNXXXXK000KK00XKOdlxXNKkkOkkkkkkkkkkkOOOOOOOO00000000K0xlcxKKkdooollllox0KXKK00000KXNNXXNXK0O00KXXXXXX0kdoddxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkOkkkkOOOOOO00000000000OOOkkxxxdolllcccloddollccccllo
lllooollc:;;,',cdkOO0000OxxkO000Okxdolc::cloodxxkxddxO0Oxdxdox0KXXXXXXKXNNXXNWWWNK0d;.':ood0NMN0dc;;::::lOKOo:oKN0xxkxkkkkxxkkkkOOOOOOOO0OO00000KOo::kXXKxoooolllox0KKKKKXXNXNXXKKXNNNXK00KKXXXXNXOxddxxxxxxxxxxxddddxxxxxxxxxxxxxkkxxxxxdddxxxxxxxxxkkkkkkkkkOOOOO0000000000OOOOkxxdddollccccloddollccccclo
llloooooolllc:;:lxO000K0OkxxxkOO0OkxdollcccccclodxkOOOkdc:oxkO00KXXXNNXXXXK00KXXXXXKOxxdc',dXXk:...'...':dOx:.;kKOdoxxxkkkkkkkkkkOOOOOOOOOO000O0Kkl;ckXNN0xdoooooodk0KXXXXNXNNXKKKKXXNXXXK0KKXXXNN0kddxxddddddxxxxdddxxxxxxxxxxkkkkkkkxxxxxxdddxxxxxxxxxxxxkkkOOOOOOOO00000OOOOOOkxddooolllllcllooollcccccll
::ccclloooooolcccoxOO0000OkxdooxkOOOkkdolc::::::coO0OkkOkkkkdldk0XNNNNXXKOd:,;codxkOKNNXOooOK0dc:lxkxddxkxdl,..l00ocokkkkkkkkOOOOkkOOOOOOOOOOO00Oo;;o0XNWXOxddddoodk0XXXXNNXXNNXKKKKXXXNNXKKKKXXNNKOxddxxxxxxxxxxxxxxdxxxxxxxxkkOkkkkkkxxxxxxddddddddddddddxxkkkkOOOOOOOOOOOOkkkkxdooooollcccclloooolc::cccl
..'',;clolloddollodxOO0000Oxl:,;oxOOOOkxdolccc:;cxOOOO000ko:;cdOKXXXXNX0xc'  .'''';dKNWWWXKKKXXOO0KKKK00Odc;,..;kKkc:lxOOOkkkkOOOOOOOOOOOOOOO00Oo;':kXXXNX0kdddollokKKXXXXNXXXXXXXKKKKXNNXXXKXKKXXXKOxxxkxxxxxxkxxxxxxxxxxkkxxkOOOOkkkkxxxxxxddxddddddddddddxkkkkkkOOOOOOOkkkxxxxxdoooollccccclloooolc:ccccc
......',;:clooolllodkO0000Oxl,..':dkOOOOxxdolc:lxOOkk0XKxl;,;cxOKKXXNKkc'.  .',,'':xKNNWWWNNNNKkxoldkkxdolc;,..'l0Kxl;:codxkkkO00OOOOOO00OOOOkdl;,:d0NNXXXKxoolllcoOKKXXKKXXXXNXXXXK00KXNXXXXXXXXXNNKOkxxxkkkkkkkkxxxxxxxkkxxkkOOOOOOOkkkxxxxxddddddddddddddddxxxkkkkkkkkkkkxxxxddooooollcccccllooolcccccccc
.... .....,;:ccllllodk000Oxl,.. ..,cdk0Okkkxoloxkxk0XNX0kdlccoxOKXXX0d;.   .',,.':dOO0XWWWWX0ko:'..;cc:::cc;'...'lxoc;,'',;codkOOOOOOO0000Okxl;',:dOXNNNK00xllclccoOKK00OO0KKXNXXXNXK00KXXXXXNNNNXNNNXKOkkkkOOkkkkkkkkkkkkkkkkkOOOOOOOOkkkkkxxxdddxxxxxxxxxddddxxxxxxxxxxkxxxxddddolllllccc::ccloollcccccccc
......    ...';:looooxkkxdc'.  .....;lxkO0OkxxkkdlldO0KKKK0OkkOKXX0d:'.....,::;;lk0Okk0KKKOl,.....:lc:cllc:,......;c:,,cooolllodxkOOOOOOkxoc,..':dOKXXXKkxOkoccc;cdk0Okkkxxk0XXXXNNNXXXXXNNNNNNNNXXNNNXKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkxxxxxxxxkkkkkkkkxxxxxxxxxxxxxdddddooolllllcccccccclooolcccccccc
........     ..';:llodxxdc,..  ......':lxkOkOOko:,'.';ok0KKKKXXKOxc,.......:olcok0000ko::l:.  ..':xxdoc,''''.. .  .;c,.:dxxxkO00OOOOkxolc;'..';:cd0XX0kxxO0kl::;;oOOOkxxo:,;d0KXXNNNNNXXXXNNNNNNNNXXNNXK00OOOOOOOOOOOOOOOOOOOO00000000OOkkkkkkkkkkkkkkOOOOOkkkkxxkxxxxxxdddddoolllccccccccccccclloolcccccccc
'''''.....      ..';:clooc;....  ......':oxO00kc,..  ..;oOKXXK0xc,........';ccldkO0Oko:,;;..   .,ldc;;;,,,,,.........''.',;cdkOkkkxdoc,....',cc:cxKKkdod0Kko::;.'oOOOOkxdc''oOKKXXXXXXXXXXXXXNNNNNXXXXK00O000000000OOOOOO0000000000000OOOOOkkkkkkOOOOO00000OOOkkkkkkxxxxxxddddollllllccccccccccloddolccccccl
'''''''......     ...'',:c;'. ...........':oOXKxc'.... .:xXXKxc,..........;::cx0KOdll:'.,'. .  .'clcloddoc:,'.......':;..',,;;,,,;;;;;;;,,;cc:;:dOOkdk0KKOo:,'. .';:dkOOxl,;xKXXXXXXXXXXXXXXXXKKKKK00000000000000000000000000000000000OOkkkkkkOOOOOO00000000000OOOOkkkxxxxxdddoooolllllllllccclloddolccccccc
,,'''''''''...         ..''.. .........   .;xXN0d;.....;d0NXOl,........'.';clx0KOo:;c:'........ .;clodddolcc:,,'.'.':c,...,,;,'...',;:cc:::::cdkOkdx0XNKxoc,..     'lkOkdc;cOXXKKXXXXKKKKK00KK00000OOOOOOO00000000000000000000000000000OkkkkkOOOOO000KK0KK000K00OOOOkkkkkkkkxxxxddoollloollllllooddolccccccc
,,,,,,'''''''...         ...   .......... .,xXN0d:'..,lOXNXKOkdl:,'.......:dOOkdoc;:cc,.''..... .':cloddollc:,...'.','....'',;;;,'.';::cloxxk000kxOKXOxdl;'.      'lkOkdlccdKXXKKKKKK00000000000OOOOOOOOOOO00000000000000000000KKK00000OOOOkOOOO000KKKKKKKK0KKK0000OOOOOOOOOkkkkkxddoooddoooooooodddoccccccc
;,,,,,,'''',,'....             .......... .c0NN0d:,;cxKNNK000OOOOkdl;'..':x0Oo:;:;;;,,;,;,'.... ..,:looooolc:,....''''''','',;::::;;;cox0KXXXK0OOKKOdlc:;'.      .l0KOkxddkKXXXKKKKK000000O00000OOOOOOOOOOOO000KK000000000000000KKKK0000OOkkOO0000000KKKKKKK000000000OOOOOOOOOkkkkxxddddddoooloodxxdolcccccc
,;,,,,,,,''''''....      ...   .........  'dNWN0xllx0KKKKXK0000000O0OxlcoOOdc;:;',;c,.',;;'..... ..;clllooool:'....',:coddlc:::cccccox0KXXXK000XKOdlc:;,.        ,kKK0OkOKKXXXKKKKK0000000O0000OOOOOOOOOOOOO0000KK00000000KK000KKKKKKK000OOOO000000KKKKKKK000000000000000O0000OOOOkkxxxxdooooooddxxdolcccccc
;;;;;,,,,,,,,,'''....             ...... .;kNNXK0KXNNKkxkOOOO0000KKXNNK00Od:,',,,,:l:'',;::,.......',:llc:;;;;,.';coxOO0KKK0OkxdddkOKKKK00OO00K0xl::;,..        .c0KK0000KXXKKKXKKKK000O00O0OOOOkkkOOkkkkOOO00000000000000KKK0KKKKKKKKK000OOO0000KKKKKKKKKK0000000KK00000000000000Okkxxxxdooooodxxxxdolccccc
;;;;;,,,,,,,,,,,,'....             ....  .lKWNXXNNXXXXKK0Odld0XXXWWWWWNKxc,,;;,,,:loc;;,,:c;.........,::,......,lk0KK00O0KXNXKOOOKKKXXK00OOO0Oxlccc:'.          .o0K000KKKKKKKXXKK00000000O0OOOOkkkOOOkkkOOO00OOO00000000000KKKKKKKKKK00000OO000KKKKKKKKKKK0000000000000000KK00000OOkxxxxddoooodxxxxdolccccc
'''',,;;;;,,,,,,,''...             .... .cONNK0KNWXKXNNWWNKkkKWWWWWWNXK0xc;,,,,,;cooc::;;c:;'.........,,'',:cldxOKK000000KKKOkxk0KKK0ko:;,;:cloool:,.           .o0K00KXXXXKKKXXKK000000000OOOOkkkkkkOOOOOO000OOO0OOO0000KKKKKKKKKKKKK0000000000KKKKKKKKKKK000000000000KKKKKKKKK000Okkxxxdddooodxxxxdolccccc
.....',;;;;,,,,'''''..            ..   .;kNNKkOKNWWWWWWWWWMNKKXNWWWWNK0000Oxo:;',lolc::;;;;,'.........';:lxOKKK00000000OO00OxxkOKXK0kl,.    'okxdl:,.           .o0KKKXXKKXKKKXKKK00000000OOOOkkkkkkkkkOOOOOOOOOOOOOOOO00KKKK0000KKKKK00OOOO00000KKKKKKKKKK0000000000000KKKKKKK000OOkkxxxddddddddxxxolcccccc
.......';;;;;,,,,'''..            .   .ckKXKOxxOKXXNWWWWWWWN0kk0XNWWWWXXKXXNX0koodoc::;:clc:,'.......;lx0KXXXKK0000KKKkxOOOkkkOKXXKkl,'..   'okkdlc,.          .,dOKKKKKKKKKKKKKK00000000OOOOOkkkxkkkkOOOOOOOOOOOOOOOOO00KKKK0000000000OOOOOO00000000KKKKK00000000000000KKK0000000Okxxxxxxxxdddddxxddlcccccc
..   ....',;;;;;;,,'..               ,d00kdddddxkdloxk0000KXXKKK00KKXXNNNNWWWWNNKkocldxkO0Oko;'.',:ldk0KKKK000KKKKK0kxxOKKKKKKK0kxdc,'',.   .lkOxol:'.         .;lk0KKK000KKKKKKKK000OOOOOOOOkkxxxxkkOOOOOOOkkOOOOOOOOO00KKK00000000OOOOOkOOOO000O0000KKK0000000000000000000000000Okxxxxxxdddddxxxxxdolccccc
... ........',;;;;,...              .c0Kxc;;::;:lc,'',:::;::codolodxddxOKXNNWWWWXOxkOKXXXXXX0koodk00000000KKKKKKK0Odod0XKXKOdl:;,,;'..,;.   .lkOxdooc,..       .':d0000000000000KK000OOOOOOOOkxxxxxxxkkkkkkkkkOOOOOOOOO000000OO00OOOOOOkkkkOOO00OOO000KK0000000000000000000000000OOkxdxxxxddxxxkxxxxxolccccc
....   ........,,,...              .;dXNKkdl:'. .;::,,',,,'. .....',,,;cdkOKXWWWNXKKKKKXXXXXXK0OO000000000KKXXXK0OxxO0K0KX0o,...,;,'..,;'   .cOOkxdxdolc;..   ..';d00OOO00000000KK0000OOO0OOkxxxxxxxxxkkkkkkkkkkkkOOOOOO0000000OOOOkkkkkkkkkkOO0OOO000KK00000000000000OOOOOOOOOOOOkxxdxxxxxxxkkkkxxxdolccccc
'...          .....             . .;xKXOxoc;'.   .'ll:,,,,,'........  ...';coxkO00KKXXKXXXXXXXKK000000000000000Oxxk00OOO0Kkl,...,;;;;;::'   .;xkxxxxxdooc;,',;:c:cx0000OO000000KKK0000OOOOOkxxdxxddxxkkkkkkkkkkkkkkkOOOO00OOO0OOkkkkkkkkxxxkkkOOOOO00000000000000000OOOOOOOkOOOOOkkkxxxxxxxxkkkxxxxddolccccc
''...                        .....,dKNOc........  .;oo:'..''.....           ...',;:ccllodxxkkOOOOOkdlcccc:clxkkxxdxkkkOOOdc,''''';::ccc:'   .,dkxxdoc;,,,;;;:cllclk00O0OO00000K0000000OO00kxxddddddxxkkkkkkkkkkkkkkkkkOOOOOOOkkkkkkkkkxxxxxxxkkOOOOO000000000000OOOOOOOOOOkkkOOkkkkxxxxxxxxxkkkxxxxxdolccccc
,,'..                      ....'',ckNN0o;,'......  .,odl:,,'''..             ...  .........................:dkkxxxxxkOOxoc,..,;,',:c:ccc,.   ,dxlc::;;;,,;clooddodO00OOOO0000000000000000000OkxddddxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxkkkkkkOOOOOOOOOOOOOOOOOOOkkkOOOOOOOkkxxxxxxxxxkkkkkxxxdddolcllo
;,'..                    ......',cxXWNKkdl;'......  ,dkdc;;;'....           ..'...,;,...            .    .:dkkxddxdxOkdccl;..,:;,;clc:cc:.   'cc,',,;lolc:clodddooxkO00OO000000000000000O00000OkddddxxxkkxxxkkkkkkkOkkkkkkxxxkkkkkkkxxxxxxxxxxxxkkkOOOOOOOOOkkOOOOOOOkkkkkOOOOOOkkxxxxxxxxxkkkkkkxxdddollodk
,'..                    ........,o0NWN0kddoc;,...  .lOOc,',,..  ....       ..';:c;'...           ...    .:dkkxddxddxxl;cxx,..,::;,:ccllll;.  .;::cc:;;:;;''':oddc,:ok0000KK000K00KKKKK000OkxxO00OkxddddxxxxxxkkkkkxxxxkxxxxxxxxkkkxxxxxxxxxxxxxxkkkkkkOOkkkkkkkkkOOkkkkkkkkOOOkkkkxxddxxxxxkkkkkkkxddoodxkkO
...                     ...''''':xXWWXOxdolc;,...  'd0k;..''..       ...'';:odxo:.     ..............  .;dkxxxxxxxxxl,;kKd'.......';clllol;. .';cll:'......;ldo:'.,cx0000KKKK0KK0KKKKKK00OxocoxkO0OkxdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkxxxxxxxxxkkkkkxxxxddxkO0OO
...                    ...'';,',ckXWNOl;'........  .lOk:....... ...,:ccc::coxxo;.     ........,;,,,'..':dOOxxxxxxkxl,;dKKo.........,:clllc'....';cl:.   .,cdxo;...':ok000KKK00000KKKKKK000ko::clkXKkddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxkkxkkkkkkkkkkkkkkkxxkkkkkOOOkkkxxxxxkkxxxkkkkkxxxkOO000OO
 .....                 ...',;;;:lkKXXkc'''''''.... .,okx:..,cllcloool:,...,cc,..      ...   ..''',,'':ok00Okxxxxkxc',d0X0c........'',;:cc'......,cdo;...:oxkdc'....,cdO0000000KKKKKKKXKK0Oxl:::cd0K0OxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxkkxxxxkkkkkkkkkkxxxxxkxxxkkOOkkkkO0KK000O
..........            ..'',,;;:ldOKXXOl;,''.......  .:k0o'.,oOOkkxl;..  .,;;'..             ........,oO0K0OOOkkOko,,oO0XO;....'...'...','. .....,:lc,..;okkxl,.','.';ok00000000KKKXXXXXXK0xl:::cccok0OxxxxxxxxxxxxxxxxxxdxxxdddxxxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxkkkxkkkkkxxxxxxxxxxkkOkkOO0KK0000O
    ........          ....'',:cd0XXNX0o;,,'..........ckOo'..,dkkxdc,...,col,.... ....  ..........  .;dO00OO00O00xc:d00KXx'....'..........  ...';clc,...'lOOd:'.',;,';lk00000000KKKKKKKKK00kocccc;',o0KOxxxxxddddxxxxxxxxddxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkxxddxxxxxxxxkkOO00KKK0OOO
  ..........             ....,lkKXXNX0o:,'....'.... .cxxl,..,oOOx:'...,lxdc'............',,;,''....;dkkxxxxxkkOxc:dKXKX0c. ...'....''...  ...';:ll:'.  .:kkc....,:c;;cxOO000000KKKKKKKKK00Od:;ll:',ckKKOxxxddddddxxxxxxxxdddxxxxxxxkxxxxxxxxkkxxxxxxxxxxxxxdddddxxxdxxxxxxxxxxxxxxxxddddxxxxxdxxkOO00000OOOO
.................        . ..:d0KXXNXOo;,;:c:,......:dOOx:..:k0Ol.  .;oxd:.  ......   ..''',;;;,';ok0OOxxkkdxkd::oOKXNNO;  ...'....''...  ..',cllc,.   .:kOl'...,clccldkO000000KKKKKKKKK000kl;clc,.':x0XOxddxxdddxxxxxxxdddxxxxxxkkkkkxxxxxxxxxxxxxxxxddddddddddddxxxxxxxxxxxxxddddddddxxxxxxxxxkkkOOOOOOOOO
 ......................... .,oOKXNNNN0xoool:'......'ck0Oo;..lOOd,  .cxkd:.           .........'';oO0000OOOOOkd:,cxOOKXXx'  ..''........   ..',ldl;.    .ck0Ol,'',cooooxkO000K00KKKKKKKK00000kdooc,...:kXKOkxdxxxdddddddddxxxxxxxkkkkkkkxxkkkkkkxxxxxxxxdddddddddddddddxxxxxxxdddddoooddxxxxxxxxxxxxkkkOkkOkk
...........................'lkKXNWNXKko:,........'..:xOkc'.'lkx;..,lk0kc.           ............cx0000000O00Oo:lxOOO0K0c.  ......'....    .'';oxl'   ..'lxOkc'.'';clooxOOO00000KKKKKKKK00000Okxdl;. .cOKXX0kxxxxxdddddddxxxxxdxkkkkkkkkkkkkkkkkxxxxxxxxxxxdddxxddddddxxdddddddddooooooddxxxddxxxxxxxxxkkkkkk
...........................ckKNWMWKxc,..';c:;'.....;xKKx;..,co;..,oOOkl.   .      .............,dOOOOkOOO0K0dloOKK00KKO:............'.    .,,;oxl'  ..,:oxxl,.......';lk00000KKKKKKKKKK000000Oxddl,':xKKXNX0Oxxxxxxxxxxxxxxxxxxxkkkkkkkxxkkkkkkkxxxxxxxxxdddddddddddxxxxxxdddddooooollodxxxddxxxxxxdddxxkkkk
..........................;xKXNNNN0o;,;cc:,'......,xXNKo,.:do,. ,dO0kc.         ............ .,lk0OkkkOOO0Odclk0XXKKNKkc,;;c;.  ....'.    .,:cdxd;. .,:ldxo;. ........,oO00000K00KKKKKK0000K00kxdlccok0XNWNXKOxdxxxxxxddxxxxxkkxxkkkkxxxxxkkkkkkxxxxxxxxdddddddddddddxxxxxxxdddooooolllodddddddddxdddddxxxxx
     ....  ...          .'l0XXXXXKOxoll:,...''...':xKX0l;lOOc. .lOKkc.        ............. .,lxOOOOOOOOOko:cx000KKNWKo,.,:dl.  ....'..   .,:lxOkl..':lodo:'   ....'..'lk000000000KKK000K00KK00xl::ldk0XNXNNN0xxkxxxxxxdxxxxxkkkkkxxkkxxxkkkkkkkxxxxxxxdddddddddxxxxxdxxxxxxxddooooolllooodddxdddddddddddxxx
          .             .:xO0KNNNKOdl:,'',,,,,,'..,x0Od:;oOd'.'ck0Ol.        ...............'lkOOOOOOOOOko::x0OkkO0XXk;. .,oo,......''.   ';:lxOkl,';lodoc,.    ..',,.,lk0000000KKKKKKK0K00K000x;.':ooooodOXXkdxkxxxxxxxxxxxxxxxxxxxkkkxxkkkkkkxxxxxxxxxxddddddddxxxxdxxxxxxxxdddooollllloodxxxxddddddddxxxx
                       .;xKKKXNN0xoc;,',::cc;,'...;kOo'..lxc';ok0xc'.      ................,lkOOOOOOOOOOd::oO0OkkO0KKd.  .;dl,'''''';;.  .,ccoxkkdc;cdddl;.      .','..ck0000000KKKKKK00K00K000x:'':c;'.',o0x:cxxxkkxxxxxxxxxxxxxxxkkkkkkkkkkkkkxdddddddxxxxxxxxxxxxxxxxxxkxxxxddooollllloodddxxxddddddddxxx
                       'oKXXNWXkl;;;:ccclol;'...,:dOx;  .;c::x0Kkc..     .................'lO0OOOOOOOOOd:;okOOOOO000Oo'..:xkl'.''',;:c;. .,loxkkkxl:odxdc,.      ..,'..;xO0OO00000KKK00KKKKKKKKOo:::::;'.;k0o';dxxkxxxxxxxxxxxxxxxxkkkkkkOkkkkkkxdddddddddddxxxxxxxxxxxxxxxxxkkxdooollllooodddddxxdddddodddd
                      .cOKKKNWKdc:cldddoll:,'..,dO0kl'  .;:ok0KOl'       .................ckOOkOOkOOOOxc;okOOOOOO00ko;'';d0O:......',:;...,cdkOOkdc:oddl,.        .,,..:dO0OO000K0000KKKKKKK0KK0kl::cc:''lO0o';dxxxxxxxxdddddxxxxxxxkkkkkkkkkkkxxdddooddddddddxxxxxxxxxkkkxxkOOkxdolllllooodddxxxxddoooodddd
                     .;xKXKKNWXkddxkkxoc::;,,,';dOOko,..;ldk00kl'      .................'cx0OkOOOkkOOxl:lO00OOO000Od;...;kKk;   ......'...,coOKK0xc:odoc.         .''..;dO000000000000KKKK000KK00xc:::;,ckK0o;:dxxxxdxxdddddxxxxxxxxxxxxxxxxxxxxxdddddxxxxxxxxxxxkxxxxxkkkOOO00Okdolllllooddddddxdddoooooood
                     .;d0NXXNNK0OOkdl:;'',;,'...cxOOd;..;dO00kl'.    ..................'lxOOOOOOOkOOkl:lkO000OO0K0x:.  .:kKx;.............;:lkKXKx:;ddl;.          .'..,lO0OO0000000000KKK00KKKK0koc::,:x0K0xccxkxxxxxxxxxxddddddddxxxxxxxxxxxxxxxxdxxxkkkxxxxkkkkkkkkkkkO00000Okdolllllooddddddddddoooooooo
                    .';lOXNNNX0Okxo:,'..',,... .lO0kl..'lOKKOl'.  .................'...:kKOO0OOOOO0Oo;cx000OO000Oxc.   'oO0d:''',,,'''''.':clxOKOl''ldc;..         ....'ckOOOO000000000KKK00KKKKK0kl;''ckKKKOolxkxxxxxxxxxxxddodddddxxxxxxxxxxkkkkxxxkkkkkkkkkkkkkkOkkkOO00KKKK0Oxolllloooddddddddddoooooooo
                    .,lx0XNWNKkdool:;,,,''...  'dK0o'..l0XXOd,.....';;,,,,'.'''.......:d0K0OOOOO00Od::x00O000K0Oxl,.  .ck0Ol,..',,,,,;;,';cllxOKOc..;c;,'''....... ..'.':xOOO0000000000KK000KKKKKX0d,..:OXNNKxokOkxxxxxxxkkkxxxxxdddxxxxxxxxxxkkkkkkkkOOOOOkkOOOOOOOOOOOO0KKKKK00Oxollloooddddddddddoooooooo
                   ..;d0XNNWNOdoool:;;:,.. ....:kKkc'.cONN0o,.....':c:;:::::cc:;,,'.';oO0000OO0O00d::x00OO000KOdc,'. .:dO0x:.........'''',:ldOKXKo,........''''''...,,,,cxOkO0000000000000000K0KKKKx;. 'xXNNXkox0OkxkxxxkkkkkkkkxxxxxxxxxkkxxxxkkkkkOOOOOOOOOOOOOOOOOOOOO0KKKKKK0Okdolllooddddddooddoooooooo
                  ...:kKXXXNXOdooolc:,.. ......cOKkc;ckNXOl'.....,cc:;::::cllllcc::cok0K0000O000Oxc:dO0OOOO0K0xc,'...,okOOd;.  ...........,cdOKXKxc'.     .....''...,;:ldkkkOO0000000000000000KKKKKOl'..lKNNXOooOKOkkkkkkkkkOOkkkkxxxxxxkkkxxxkkkkkOOOOOOOOO000OOkOOkkkO00KKXXK00Okxollloodddddooddddooolllo
                  ..'l0XXKXXXklccc:;.... ......cOXOc,lOKkc......;cc:,;:c:cclllllc::oOXNNXKKXKK00xc:dO0OOOOO00kl,'''.'cxOkxc'.  ..........'',lkO0ko,.....     ........;okkkkkO000000000000000000KKKK0kl;;l0NNXkc:xKK0OkOOOOkkOOkkkkkxxxxxxxxxxxkkOOOOOO000O00OOOOOOOkkkkO0KKKXXK000Oxdolloodddddddddddooollll
                  ..,o0XKKXN0o:::;'.......... .cO0o,,oOkc'.....;c::;::cccllllcllcclxKNNNNXXNNXK0dcdO0OO0000KOl,.','':dkOxo,.  .............'cxkOx;. ............  .  'oO0kkkO000000000000000000KKKKK0kdod0NWNOlcOXK0OOOOOOkkkkkkkkkkkxxxxxkxxkOOOkOO0000000OOOOkkkkkxxkO00KKKK00OOOkdooooodddddddddooooollll
                   .;xKXKXXXOo::,............ .lOd',lkkl'....';::;;:llccloollllllox0NNNXNNXXNXKkdx0XK00000KOl,..',',okkko:.. .............';lxkkd,..''..',,,''.....  .ck0OkkOO000000000000000000KKKKK0kdoONWW0dxXNK00OOOOOkkkkkkkkkkkkxkkkkkkkkOkkOO000O000OOOOkkxxxxxkOO000000OOkkxdooooddddddddddoooolllll
   .               .:kKKKXXKOo;...........   .;xO:.cOOl.......'''',;;:::lllllllclx0XXNXXXNXXNXOdx0XNNXXKKK0o,..'.'.'ldxxc... ............',:oxOkl...;' ..'',,''''.....;dkOkkkOOOO0000000000000000K00KKOdokXWW0dONWX0OOOOkkkkkkkkkkkkkkkkxxxkkkkkxxkOOOOOOOOOOkkxxddxdxxkOOOOOOOkkkxdooooodddddddddddooolllll
                   .:kKXXNXOl;.......... .  .;x0x;:k0x;. .''',;:;,;;,''',,;;:cllo0XNXXKXXNXXX0xdOKNNXXXXXKOo;'''.''.;oxl'..  .........  .,;ldxOx:..,c,   ..........',';lxkkkkOO0OO000000000000000K000K0koxXWNOdONWX0kkOkkkkkkkkkkkkkkkkxxxxxxxxkxxkOOOkkOkkxxxxdooddddxxkkOOOOOkxxxdooooooodddddddooooolllll
                  ..:kKKXKkc....'........   ;kXk:;dOx;....,,,:ccccllc:cc:::;;,;cx0XXXXXXXXNX0kxkKXXXKXXNX0xlccc:,,;,,:c,...   ...........,:lxkkd;..;o:..      ......'';lkkkkkOOOOO0000000000000000000KKOxkXNKxoOXNX0kkkkkkkkkkkkkkkkkkkkxxxxxxxxkkOOOkkkkkxxdddoooooodddxxxkkOkkxddoooooddddddddddooooolllll
   ........  ......'ckKKKOo,...''''........'o0kc'lOx:....''',:cccllcclloolllcllx0KK0KXXKKXX0xdkKXXXXXNNX0xlccll:;:c:;,'....    ...... ..',:oxkOd' .cxc..  .   ..  ....;dOOkkkOOOO000000K0000000000000KK0kOXX0olkXNXOxxkxkkkxkkkkkkkkkkkkkkxxxxxkkkkkkkkkkkxxddoooooooodddxxxxkkxddoolooodddddddddooooollllll
...................'lOKK0Od:'.''''........;:ll,':kOc...',''';ccccccclllllllcldk0XNXXXXK0KX0xod0NNXXNXNNXOdccllc::cc::,.....    .....  ..';:ldkko' .cko,.     ...     .,dOkxkkO0OO000000000000000000000KK0KNN0ocdKNKkdxxxxxxxkkkkkkkxkkkkkkkxxkkkkkkkkkkkkkxdddoooooooooddddddddddoooloooooodddddddooooolllll
...................'dKXK0Okl,.'''...',,,,,;;;,.;kOo,..,'',;:cccccccclllllllclx0XNNXXXXKKXXkookKXXXNXXNNKxocllc:;:cc::;'...     .....  ..';;cdOkc. .:Od;.             .,okkxkkOOOOO00000000000000000000000KXWNkldKWXkddxxxxxxkkkkkkkkkxxkkkkkkkkkxxxxxxkkkkxxxddoooooooooddddddooooollooooooooodddddooollllll
...................,d0K0O0Oo,',;,,;;:::,...;:,,lkd;'.,,',:clccclccccllcllllldOXNXXXXXXXXX0xxOKXKKKXKXXKkolllc;;:cc:;;;;'...     .'..  .'',;:dkx:. .:Oxc,.           .,lxOkxkkOOOOO0000000K0000000000000000KNWKxxXWXxodxxxxxxxxxxxxkkkkkxxkkkkkkkxxxkkkkkkkkkkkkxdddddoooooooooollllloooooodddoddxxxdolllllll
...................;xOOO0K0d:;::;;;;;,.. .;o:.;lc'......',,;;;:cccllllllllldOKXNXXXXXXNNKkdOXNXKXXXXK0xc::c:;,;:::,',,,,'..     .'.. ..,'',:dkd;. .c0Oo;.      ..  .'lkK0kxxkOOOO0000000000000000000000000KXNKkkXWXkoodxxxdddxxxxxxxxxxxxxkkkkOOOOOOOOO00OOOOOOkkOkkxdooooooooollllllooooodxxddxxkxdoolllllc
...................:xkO0KXKxc::;,'.''.. .:oo'.cl;..............',;:c::ccccokKNNNXXXXXXNXOxx0NNXXXXNNXOo;,,,'.',;;,,,,;;;,....  .',.  .,;;,,:dkd,  .c0Kkl.  ..  ... .'ckK0kxxxkOOO00000000000000000000000000KXKOOXWXkolodxxddddddxxxxxxxxxkkOO00000000000000OOOOOO0OOxddddddddolllllllooooodkkkkkkkkxdolllllc
................ .;ddoxKXN0o;'....',:;,,cxkc';c;.................'''''''';lOXNNNNNNNXNNKkxOXNXXXXXNNKkollc:,,,,,'...',:c:;'... .;:.  ':l:,;cxko'  .c0K0d'   .  ..  .,:dOkxdxkO00OO00000000000000000000000000K0OOKNNOdoodxxxddoddxxxxkkkkkOOO000000000000000OOOOO00OOkxxxkkxdoollllllooooooxkOOOOOOkxdolllllc
................ .oKOdx0XXk:...',;;:c:;cxOd,.;;.. ...............','''...,o0XXKKXXNXXNKkxOKNNXXNXXNXOdlllc:;;:cc;,,,',:lc;'.....;;. .'cc:;cx0Ol'..'lOKKk;.  ..    ..,:ldoodxkO0OOO000000000K0000OOOO000000000OkxOXNXOdloddddoodxkkkkOOOkOO000000000000000OOOOOOO00OOkkkkkxdooooolllodddxddkOOOOO00Oxdlllllll
..............   'xKKOOKK0o,.,;:c::;,,cx0Ol',;'.................''''''..,lkKXK00KKKKXKkdkKXXXXXXXXXKkoclc:;;:cc:;,;:;;ll:,'.....;;. .;cc;cd0K0o,..;oOKXOc.  .    ..';:cc::oxkOOOOO000000000KK00000000000O000K0OO0NWWXKOkxxddxxkkOkkkOOOOO00000000OOOOOOOOOOOOOOOOOOOOOkkxdddxxdoooddxxkkxxkO00OO00Oxdollllcc
............     .cxOOO0KKkc;::;,''..'oO0xc,;;..................''''''',cx0KXKKK000K0xclkXXXXXXXXNX0xlccc:::::;,,'',,;:c:,'.....;;. .;lc:oOKK0o,.'cx0XNKl.       ..';::;,;oxkkOOO000000000000000000000000OO00000KKXKOk0XX0OkOOOOOOOOO00OO0OO000OOOOOOOOOOOOOOOOOOOOOOOkkxxxxddoddxkOOkxxdxkOOOO000Okdlllllcc
.........        .':dO00KX0o;,'......:kK0d::;..................''''''.':d0K0KKKK00KKkc:d0K00KKKKXNKxolllc:ccc:;,''',;:c:;;,.....,:'..:lclx0KK0o'.;oOKNWKl.  ..   ..';:;'.,lxkkOOO00000000000000000000000000000000kOx;':kNNK00OOOOOO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxddoodxkOOOkxxxxxkOOO0000Okdllllccc
 .....          ....cOKKKKOl,...... 'd0KOl,,'.................','.'''.'lkKK000K000Kkc:o0K0O00000KOdc:ccc::cccc;,;;,,;col;,'.....';,..:llokKXK0l'.;x0XNN0l.   ..   .',;,..,lxkkOOO000000000000000000000000O0000000OkkocokXXXK0OOOOOOOOOOOkkkkOOOOkkkkkkkOOOOOOOOOOOOOOkkkxdddxkkkOOxddxkOOkOOO00000Okdolllccc
 ....           ....ck0KKOd;...... .;x00d;........ ..........'''.'''..;d00000000000d:oOK000K000K0d;''''',,;:;;;,;;,,:oxc'..... ..','.;clokKXKkc''ck0KKKkc..      ..,;;,.,coxxkkOO000000000000KK000000000000O000000KXNNNNXK0OOkOOOOOOOOOkkkkkOkkkkkkkkkkkOOOOOOOOOOOOOkkkxxxkkOkkxdodxO000OO0000000Okdolllccc
   .            ...'cxOKKkl'...... .ck0Ol'....... ...........''..','.,lO0000O00000xllk0KK00K00K0xc'.'...........',';lkOo,'.......,,,,:::ok0KOo;';o0X0OOd;'.....  .,;;;;:loodxkkkO0000000000000000K000000000O000000OkO00000OkkkkkOOkkkkkkkkkkkkkkxxkkkkkkkOOkkkOOOOOkkkkkkkkkOOkdoodxOOO00O00000000Okdolllccc
                ....:dk0Kkc..... ..,dOOxc'.. ..  ............''.'''',ck0K0OOO0000OolxKKK00KKKKKOl,..''.............,d00d;,,'....';;;;:;,lk0Kkc..,oKXKkxl;''......:c;;::cccldxkkOOOO00000000000000000000OO0OO0OO00kl'.'';oOKKOkxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkOOkkOkkkkkkkkkkxxdddxkOOOOO000000OOOOkxollcc::
    .           ....:xO0Kkl'.... ..:x00d,......  ...............''..:x0K00000O000kloOKKKKKK0KK0x:'''...............:kK0o;;,,....,,,',;,':kKXk:..,d00Odc;'''.....;do;;clllcldxkkkOOO0000000000000000000OOOOOO0OO0Ox;....':okOOxxddddddddddddddddxddxxddxxkkkkkOOOkkkkkkkkkxxxxdddxkOOOOOOOO00000OOOkkxdlccc::
  .......   .. .....cO00KOd;.......:x0Oc.. ....  ...........'''''..,oO0000000O00Oo:d0KKK0KKKKKOl'..'..............,dKXOo;;;,'...,,'',;,.;xKKx;.'lOXKOo;,..''...'cxd::llllcloxkkOOOO00000000000000000000OOOOOOOO0Ol'...'',;coxxdddooodddoddddddddddddddxxkkkkkkkkkkkkkkkkkxxxxxxxkkOOOOOOkkO000OOOOkxdolcccc:
  ................ .:kOO0Kkc....  .lO0k;......................''..,lk00000O0000Kx:ckK000000KX0d;.................'o0XKOo;;;;'...,;,,;::;cx0Kd'.;dKXKkc,,,,,,...:dkxc;:::clloxkkOOOO000OO000K000K000000000000O000d;..''',:lodxxdddooooooooodddddddoooddxxxxkkkkkkkkkkxxxxxxxxdddxxxkOOOOkxkkOOOkOkkkxdollccc:
      ..............;xO0KKx;. ....;xKKk:,;;;:::::cc::;,,,,,,''''',:d0K00KK0000KOl;lOK00000KKKkc'.................ckKX0kl;;;;'...,;,';lllok0Ol'.:kXNKd;'',;;,'.'oO0x;.';codoodxxkOO000OOO000000000000000000OOO0Oxl;,,,,;:cldxxxddddooodoooooooooooooodddxxxxxxkkxxxxxxddxxxxddddddxxkkkxxdxkOOOkkkkkxxdolcccc
 ... ...............;x0KK0o'.....'l0NKd,..'';:cclooolllllllcc::;:cdOKK0000000KOo;cx0K00K00KKOl,............... .,dOKKOo;.'''....''..':lclx0x:',l0NNKd,.',,,,..,d00o''cl;'',:oxxkOOO00OOO000000000000000000OOOkxdl:::;,'',:looooddoooooooooooooodooodddddxxdddxxxxxxxxddddddddddddxxxxxdddxkOOkxxxxxxddolccc:
 ...................;d0KKOl'.....'oKNKo.    ..',;::::cclllloooolokKXXKKK000000x:;d0K0O00000Od;.................'lO0K0x:....... ......:c:cdko'.;d0NX0o,..,,,'..'okx:.,c:'.. .cxxkkOOOO0O0000K0000000000000Okkkxdl:,'',,,;:cccloodoolllooooooooooooddddddddddddddddddddddoooodddddddddddddddkOkxxxxxddddollcc:
  ..................,oOKKOl,......oXN0o'... ........''',,;;:ccclx0NWNXXXXXKKKOl:lkK000000K0xc,.................:k000Ol,........... .';:::lo:..:xKNXOc'..',;;'.:xxl.  .,;;. .;oxkkOOO00000000K0000000000OkxxOKOo:''.';:ldkkdolooddolllllooooooooooooooooddddoooddddddoooooooodddddddoooddddxkxxdddxdddddolcc:
   ......''''.''..'.'ckKXkl,'.....oXXOl;,,,'',,,,,,'''..'''''',ckKXXXXXXNXXNXkloO0K000000KOl,.................,d000Ol,....... .... .';::ccc,..ck0KKd;'''',::;;oOx;.  ....   .;oxkkOOO000KK000K0000000Oxo:,;o0K0xl;'';lx0XXKKOkkxxdolllllloooooooooooooooooooooooooooooooooo
          [FBB+ Facebook Bruteforce Tool]
        [@Created By SHAH ELYAS] """+C+p+"""
              Youtube Channel: Somali 4You
              Facebook Page: Hal moshklat facebook""
        cabdulahi.sleep(2)
        print
        
        
        
        
       
